name: Generate Snake

# This schedule runs the action every day at midnight
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository content
      - uses: actions/checkout@v2
      
      # Generate the snake animation
      - uses: Platane/snk@v2
        with:
          github_user_name: Hariprasath36
          outputs: dist/snake.svg

      # Push the snake.svg to the output branch
      - name: Push Snake
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
