name: Generate Snake Animation

# This workflow runs every day at midnight UTC
on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 UTC daily

  # Allows the workflow to be manually triggered
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: Hariprasath36  # Replace with your GitHub username
          outputs: dist/snake.svg

      # Push the generated snake.svg to the output branch
      - name: Push to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
